### PR TITLE
Media oembed

### PR DESCRIPTION
**Pull request by adamdelaney**
## See sitenow_custom_profile PR #194.
Please make comments in regards to this PR on the custom profile: https://github.com/ITS-UofIowa/sitenow_custom_profile/pull/194

### CODE REVIEW

**Comment by genjohnson** [comment]
I've successfully embedded YouTube videos, Tweets and Twitter timelines.

However, I haven't gotten Facebook to work. Do anyone have an example of this working with Facebook?

**Comment by adamdelaney** [comment]
@genjohnson Facebook has some pretty strict permissions for getting posts. Post that can be embedded must be public. Try this url: https://www.facebook.com/NPR/posts/10156101999901756

**Comment by genjohnson** [comment]
@adamdelaney thanks, that worked!

**Comment by joewhitsitt** [comment]
_protip if testing: oembed is needed (not currently in sites/all)._

I tested it on IP locally and the conversion worked well except for about seven videos (some very recent) where I got the following:

```
WD oembed: Error fetching data from http://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_MDD7kXXX40%2Fl%2FPLIotX-NLOMxdCEAVTn5c-dEgi_lekt1Y9.
filesize(): Unable to find the wrapper "oembed" - did you forget to enable it when you configured PHP? file.inc:614
filesize(): Unable to find the wrapper "oembed" - did you forget to enable it when you configured PHP? file.inc:614
filesize(): stat failed for oembed://https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D_MDD7kXXX40/l/PLIotX-NLOMxdCEAVTn5c-dEgi_lekt1Y9
file.inc:614
Processed file 26181
```

I tried the following with success:

- Vimeo (alignment worked)
- Instagram (alignment doesn't work)
- Twitter (tweet and timeline) (alignment doesn't work)
- Soundcloud (alignment doesn't work)

Should we hide display as options for these?

**Comment by joewhitsitt** [comment]
@adamdelaney your fix appears to have solved the fetching errors except for videos that no longer exist (3), which I think is expected. Those three still gracefully fallback to a generic file link to the youtube page so I think we are good with that issue.

**Comment by joewhitsitt** [comment]
As mentioned in the meeting this morning, it would be nice (though probably not a deal breaker) to retain the youtube video sizes, or figure out how to make the youtube transition more transparent.

**Pull request merged**
