### PR TITLE
Support Media 2.0

### PR DESCRIPTION
**Pull request by brandonneil**
This pull request does the following:

Sets a variable that allows for the Media WYSIWYG alignment to be exposed on media embedded file entities.

Ensures that the site is using the `file_entity` wysiwyg renderer instead of the legacy `field_attach` renderer.

Tweaks logic that removes the container div around embedded file entities from being unset all the time, to being unset only for embedded documents.

Sets a new variable, `sitenow_media_wysiwyg_legacy_tokens`, to be used to determine if logic below needs to run.

In the WYSIWYG, on render, an existing `float:left` or `float:right` will be removed and the corresponding media wysiwyg alignment class will be added to the embedded file entity container. Additionally, any instances of `margin`, `margin-top`, `margin-right`, `margin-bottom`, or `margin-left` will be removed from the inline styles on the file and moved to the wrapper.

### CODE REVIEW

**Comment by brandonneil** [comment]
The next phase of work after this PR would be in https://github.com/ITS-UofIowa/sitenow_media/issues/7 if we can get it to work. Although I think that issue is more of a "nice to have" than requirement.

**Comment by brandonneil** [comment]
This PR can be easily tested by setting your system.make.yml file to use the `media-stable` branch of the custom profile https://github.com/ITS-UofIowa/sitenow_custom_profile/tree/feature/media-stable

**Comment by briand44** [comment]
I haven't had much time to test this yet but it seems the alignment piece is working well, at least for new content. I did notice there is a new view mode, WYSIWYG, that is now available when adding media in the WYSIWYG.

**Comment by brandonneil** [comment]
We should unset the new view mode like we're doing with the legacy view modes.

**Comment by markahrens** [comment]
We need to disable alignment in the CKEditor Image dialog

**Comment by markahrens** [comment]
Check the shorthand margin properties when adding both vspace and hspace.

**Comment by markahrens** [comment]
Adjust the z-index for the media browser to handle the full screen editor.

**Comment by adamdelaney** [comment]
Adjusting the z-index for the media browser pop-up has no effect. It appears as if a non-core version of jquery update is used for the administration theme, this will break the injection of style class properties for the pop-up. I'm not sure how we want to handle this.

**Comment by genjohnson** [comment]
`margin` is an allowed style in the Filtered HTML text format, so setting both vspace & hspace on an image through the CKEditor image dialog is okay.

The margin provided by the Media module when an image is floated is added to a div that wraps the image (rather than the img tag itself), so if a user floats the image using the Media alignment field and sets vspace & hspace through the CKEditor dialog, the image will have double the margin because the vspace & hspace are added as margin directly in the img tag.

Here's an example...
Margin added through CKEditor vspace & hspace:
screenshot 2017-05-30 12 34 46


Plus margin added by Media due to alignment selection:
screenshot 2017-05-30 12 35 09

**Comment by adamdelaney** [comment]
I've attempted to add the css using hook_preprocess_media_dialog_page(), however it does not appear to be attaching my css.
```
function sitenow_media_preprocess_media_dialog_page(&$variables) {
  $variables['page']['content']['#attached']['css'][] = array(
    'data' => '.ui-widget-overlay {z-index: 9999; background: red;}',
    'type' => 'inline',
  );
  $variables['page']['content']['#attached']['css'][] = array(
    'data' => '.ui-dialog.media-wrapper {z-index: 10000;}',
    'type' => 'inline',
  );
}

**Comment by adamdelaney** [comment]
I've attached the css to page using hook_preprocess_page() in sitenow_media.module. This probably is the best way to do this, but I cannot find a better way to attach this css.

**Comment by brandonneil** [comment]
SiteNow WYSIWYG update for disabling the align field in the CKEditor image plugin: https://github.com/ITS-UofIowa/sitenow_wysiwyg/pull/17

**Comment by brandonneil** [comment]
The pull request now moves any set margin (margin, margin-top, margin-bottom, margin-left, margin-right) from the inline file itself to the wrapper div instead of unsetting it. This will allow a more consistent experience for users who already have margins set manually.

**Comment by briand44** [comment]
Works as expected on existing site.

**Comment by genjohnson** [comment]
sitenow_media_uninstall() is declared twice - line 18 & line 59

**Comment by genjohnson** [comment]
I've reverted the commit that added the second implementation of sitenow_media_uninstall() so that we can continue testing. We'll get the uninstall hooks sorted out tomorrow.

**Pull request merged**
